import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import RMlogo from "../logos/rickandmortylogo.png";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Star wars</h1>
      </div>

      <div>
        <h1>Pokemon</h1>
      </div>

      <div className={styles.RMcard}>
        <Link href="rickandmorty">
          <Image
            src={RMlogo}
            alt="rick and morty logo"
            width="300"
            height="100"
          />
        </Link>
      </div>
    </div>
  );
};

export default Home;
